export { default as AboutCard } from '../pages/about/AboutCard';
export { default as Button } from './Button';
export { default as BackgroundStripes } from './BackgroundStripes';
export { default as Card } from './Card';
export { default as Container } from './Container';
export { default as Footer } from './Footer';
export { default as Heading } from './Heading';
export { default as NavigationBar } from './Nav';
export { default as TeamDetails } from '../pages/about/TeamDetails';
